[package]
name = "rustfest-2017"
version = "0.1.0"
authors = ["Tomasz DrwiÄ™ga <tomusdrw@gmail.com>"]

[dependencies]
web3 = "0.0.5"
lettre = "0.6"

[dependencies.bigint]
version = "4.2"
features = ["std"]
